//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados_selecionados
    {
        public empleados_selecionados()
        {
            this.R_Evaluacion = new HashSet<R_Evaluacion>();
        }
    
        public long id { get; set; }
        public Nullable<long> id_empleados { get; set; }
        public Nullable<long> id_periodos { get; set; }
        public Nullable<byte> estado { get; set; }
    
        public virtual periodos periodos { get; set; }
        public virtual ICollection<R_Evaluacion> R_Evaluacion { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
