//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.empleados_selecionados = new HashSet<empleados_selecionados>();
            this.R_Evaluacion = new HashSet<R_Evaluacion>();
        }
    
        public long id { get; set; }
        public string cedula { get; set; }
        public string Nombre { get; set; }
        public string tipo { get; set; }
        public string Departament { get; set; }
        public string Area { get; set; }
        public string SubArea { get; set; }
        public string CrewCd { get; set; }
        public string RosterPosition { get; set; }
        public string Unit { get; set; }
        public Nullable<long> id_user { get; set; }
        public string email { get; set; }
        public string liderado1 { get; set; }
        public string liderado2 { get; set; }
        public string liderado3 { get; set; }
        public string liderado4 { get; set; }
        public string liderado5 { get; set; }
        public string par1 { get; set; }
        public string par2 { get; set; }
        public string par3 { get; set; }
        public string jefe { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<empleados_selecionados> empleados_selecionados { get; set; }
        public virtual ICollection<R_Evaluacion> R_Evaluacion { get; set; }
    }
}
