//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Drummond02Entities : DbContext
    {
        public Drummond02Entities()
            : base("name=Drummond02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<competencias> competencias { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<empleados_selecionados> empleados_selecionados { get; set; }
        public virtual DbSet<evaluacion> evaluacion { get; set; }
        public virtual DbSet<periodos> periodos { get; set; }
        public virtual DbSet<preguntas> preguntas { get; set; }
        public virtual DbSet<preguntas_competencia> preguntas_competencia { get; set; }
        public virtual DbSet<R_Evaluacion> R_Evaluacion { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
