//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacion
    {
        public evaluacion()
        {
            this.periodos = new HashSet<periodos>();
            this.competencias = new HashSet<competencias>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public string tipo_de_evaluacion { get; set; }
        public Nullable<byte> estado { get; set; }
    
        public virtual ICollection<periodos> periodos { get; set; }
        public virtual ICollection<competencias> competencias { get; set; }
    }
}
