//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodos
    {
        public periodos()
        {
            this.empleados_selecionados = new HashSet<empleados_selecionados>();
            this.R_Evaluacion = new HashSet<R_Evaluacion>();
        }
    
        public long id { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> fechafinal { get; set; }
        public string metodologia { get; set; }
        public Nullable<int> Tmuestra { get; set; }
        public Nullable<long> id_evaluacion { get; set; }
        public Nullable<byte> estado { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<empleados_selecionados> empleados_selecionados { get; set; }
        public virtual evaluacion evaluacion { get; set; }
        public virtual ICollection<R_Evaluacion> R_Evaluacion { get; set; }
    }
}
