//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Evaluacion
    {
        public long id { get; set; }
        public Nullable<long> id_periodo { get; set; }
        public Nullable<long> id_empleados_selecionados { get; set; }
        public Nullable<long> id_competencia { get; set; }
        public Nullable<double> resultado { get; set; }
        public Nullable<long> id_evaluado { get; set; }
        public string tipo_evaluacion { get; set; }
    
        public virtual competencias competencias { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual empleados_selecionados empleados_selecionados { get; set; }
        public virtual periodos periodos { get; set; }
    }
}
