//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_usuario
    {
        public long id { get; set; }
        public Nullable<long> tipo_usuario1 { get; set; }
    
        public virtual Usuario_Tipo_usuario Usuario_Tipo_usuario { get; set; }
    }
}
