//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Tipo_usuario
    {
        public long id { get; set; }
        public Nullable<long> idtipo_usuario { get; set; }
        public Nullable<long> id_user { get; set; }
    
        public virtual tipo_usuario tipo_usuario { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
